name: Publish Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
          
      - name: Log in to Github
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fetch latest github release
        run: |
          sudo apt-get update && sudo apt-get install jq -y
          THIS_REPO=https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest
          TARGET_REPO=https://api.github.com/repos/mayswind/AriaNg/releases/latest
          echo "CURRENT=$(curl $THIS_REPO | jq -r '.tag_name')" >> $GITHUB_ENV
          echo "TARGET=$(curl $TARGET_REPO | jq -r '.tag_name')" >> $GITHUB_ENV
          echo "ARIANG_VERSION=$(curl $TARGET_REPO | jq -r '.tag_name')" >> $GITHUB_ENV
          echo "BUILDDATE=$(date --rfc-3339=date)" >> $GITHUB_ENV
        id: releases

      - name: Test Variables
        run: |
          echo ${{ env.BUILDDATE }}
          echo ${{ env.TARGET }}
          echo ${{ env.CURRENT }}
          echo ${{ env.ARIANG_VERSION }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push Docker image AMD64
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            "ARIANG_VERSION=${{env.TARGET}}"
            "BUILD_DATE=${{env.BUILDDATE}}"
            "VCS_REF=${GITHUB_SHA::7}"
          platforms: linux/amd64
          tags: ghcr.io/almir1904/ariang-docker:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create new Github release
        #if: ${{ env.CURRENT }} != ${{ env.TARGET }}
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TARGET }}
          allow_override: true
          name: Update to AriaNg ${{ env.TARGET }}
