name: Publish Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
          
      - name: Log in to Github
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fetch latest github release
        run: |
          sudo apt-get update && sudo apt-get install jq -y
          THIS_REPO=https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest
          TARGET_REPO=https://api.github.com/repos/mayswind/AriaNg/releases/latest
          echo "current=$(curl $THIS_REPO | jq -r '.tag_name')" >> $GITHUB_STATE
          echo "target=$(curl $TARGET_REPO | jq -r '.tag_name')" >> $GITHUB_STATE
        id: releases
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push Docker image AMD64
        uses: docker/build-push-action@v2
        env:
          ARIANG_VERSION: ${{ steps.releases.outputs.target }}
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64
          tags: ghcr.io/almir1904/ariang-docker:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create new Github release
        if: steps.releases.outputs.current != steps.releases.outputs.target
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.releases.outputs.target }}
          name: Update to AriaNg ${{ steps.releases.outputs.target }}
